spring:
  application:
    name: functionalProgramming
  h2:
    console:
      enabled: false
      path: /h2/db
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml